/*
    !!!!!!!!!!!!!!!!!!!!!!!!!!!    !!!!!!!!!!!!!!!!!!!!!!!!!!!    !!!!!!!!!!!!!!!!!!!!!!!!!!!    !!!!!!!!!!!!!!!!!!!!!!!!!!!
	!! DO NOT EDIT THIS FILE !!    !! DO NOT EDIT THIS FILE !!    !! DO NOT EDIT THIS FILE !!    !! DO NOT EDIT THIS FILE !!
    !!!!!!!!!!!!!!!!!!!!!!!!!!!    !!!!!!!!!!!!!!!!!!!!!!!!!!!    !!!!!!!!!!!!!!!!!!!!!!!!!!!    !!!!!!!!!!!!!!!!!!!!!!!!!!!
*/
if !(isServer) exitWith {};

#include "functions.sqf"
#include "config.sqf"
#include "classes.sqf"
#include "blackLists.sqf"


// L_ambiDrive_mainArray   = [];
L_ambiDrive_nextSpawn	= 0.5;
L_ambiDrive_lastIndex	= 0;
L_ambiDrive_currentCivs	= 0;
L_ambiDrive_posCache	= [];
L_ambiDrive_civs = [];
L_ambiDrive_players = [];

[{
	call L_ambiDrive_fnc_spawnManager;
}, 0.25] call CBA_fnc_addPerFrameHandler;
/*
    !!!!!!!!!!!!!!!!!!!!!!!!!!!    !!!!!!!!!!!!!!!!!!!!!!!!!!!    !!!!!!!!!!!!!!!!!!!!!!!!!!!    !!!!!!!!!!!!!!!!!!!!!!!!!!!
	!! DO NOT EDIT THIS FILE !!    !! DO NOT EDIT THIS FILE !!    !! DO NOT EDIT THIS FILE !!    !! DO NOT EDIT THIS FILE !!
    !!!!!!!!!!!!!!!!!!!!!!!!!!!    !!!!!!!!!!!!!!!!!!!!!!!!!!!    !!!!!!!!!!!!!!!!!!!!!!!!!!!    !!!!!!!!!!!!!!!!!!!!!!!!!!!
*/
